version: "3.8"

services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    image: spark-custom:4.1.0
    container_name: spark-master
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-master --port 7077 --webui-port 8080"
    ports:
      - "8080:8080"
      - "7077:7077"
    networks: [spark-net]
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
      - ./requirements.txt:/opt/requirements.txt

  spark-worker-1:
    image: spark-custom:4.1.0
    container_name: spark-worker-1
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077 --webui-port 8081"
    depends_on: [spark-master]
    ports:
      - "8081:8081"
    networks: [spark-net]
    volumes:
      - ./data:/opt/spark-data
      - ./requirements.txt:/opt/requirements.txt

  spark-worker-2:
    image: spark-custom:4.1.0
    container_name: spark-worker-2
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077 --webui-port 8082"
    depends_on: [spark-master]
    ports:
      - "8082:8082"
    networks: [spark-net]
    volumes:
      - ./data:/opt/spark-data
      - ./requirements.txt:/opt/requirements.txt

networks:
  spark-net:
    driver: bridge
